kind: pipeline
name: default

steps:
- name: test
  image: golang:1.19
  environment:
    GO111MODULE: on
  commands:
  - go test -v -cover ./...
  volumes:
  - name: deps
    path: /go

- name: build
  image: golang:1.19
  environment:
    GO111MODULE: on
  commands:
  - sh scripts/build_all.sh
  - sh scripts/bundle.sh
  volumes:
  - name: deps
    path: /go
  when:
    event: [ push, tag ]

- name: publish
  image: plugins/github-release
  settings:
    files:
      - release/drone_*.tar.gz
      - release/drone_*_checksums.txt
    api_key:
      from_secret: GITHUB_TOKEN
  when:
    event: [ tag ]

volumes:
- name: deps
  temp: {}
